AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Auto Scaling group.
 
Parameters:
  VPCId:
    Type: String
    Default: 'vpc-018de1caf38bc8133'
    Description: VPC ID where the instances will be launched.
 
  SubnetId1:
    Type: String
    Default: 'subnet-0e1bbd6544b12f55d'
    Description: First subnet ID for the Auto Scaling group.
 
  SubnetId2:
    Type: String
    Default: 'subnet-05f48ce96343ca6c4'
    Description: Second subnet ID for the Auto Scaling group.
 
  AMIId:
    Type: String
    Default: 'ami-00beae93a2d981137'
    Description: AMI ID to use for the EC2 instances.
 
  InstanceType:
    Type: String
    Default: 't2.micro'
    Description: EC2 instance type.
 
  KeyPairName:
    Type: String
    Default: 'MyKey'
    Description: Key pair name for SSH access to the instances.
 
Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
 
   ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ASG-Template
      LaunchTemplateData:
        ImageId: ami-00beae93a2d981137
        InstanceType: t2.micro
        KeyName: MyKey
        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
        UserData:
          Fn::Base64: |
            #!/bin/bash
            echo "<h1>Hello, World from EC2!</h1>" > /var/www/html/index.html
            yum install -y httpd
            service httpd start
 
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetId1
        - !Ref SubnetId2
      LaunchTemplate:
       LaunchTemplateId: !Ref ASGLaunchTemplate
       Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber

      MinSize: '2'
      MaxSize: '3'
      DesiredCapacity: '2'

 
 